language: python
python:
  - "2.7"
install:
  - "pip install coverage coveralls pytest"
services:
  - rabbitmq
script:
  - "coverage run --source=txamqp setup.py test"
after_success:
  - coverage report
  - coveralls
